apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        ports:
          - containerPort: 5000
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.livenessProbe }}
        readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        env:
          - name: CHART_VERSION
            value: {{ .Chart.Version }}
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
      - name: {{ . | quote }}        
      {{- end }}
      {{- end }}