apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP    
      targetPort: 5000
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort )))}}      
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}      
  selector:
    app: {{ .Release.Name }}