# Default values for flask-to-learn-containers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: robertsilvatech/flask-to-learn-containers
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets: []

service:
  type: NodePort
  port: 5000
  nodePort: 30000

resources: {}

readinesProbe: {}
livenessProbe: {}

env:
  COLOR: yellow